[tool.poetry]
name = "simplegep"
version = "0.1.0"
description = "A simple implementation of GEP variants."
authors = ["moshe <moshebeutel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
#python = ">=3.11"
#torch = "^2.3.0"
#torchvision = "^0.18"
#tqdm = "^4.66.4"
#wandb = "^0.17.4"
#backpack-for-pytorch = "^1.7.1"
#six = "^1.17.0"
#scipy = "^1.17.0"
#matplotlib = "^3.10.8"
#scikit-learn = "^1.8.0"
#pandas = "^3.0.3"

python = "3.8.13"
torch = "^2.3.1"
torchvision = "^0.18.1"
tqdm = "^4.66.4"
wandb = "^0.17.4"
pyeeg = {path = "pyeeg"}
#pFedGP = { path = "./pFedGP/", develop = true }
#pFedGP = { git = "https://github.com/moshebeutel/pFedGP.git"}
backpack-for-pytorch = "^1.6"
pandas = "^1.5"
matplotlib = "^3.7"
tables = "^3.8"
gpytorch = "^1.3"
pypolyagamma = "^1.2.3"
scikit-learn = "^0.24"


[tool.poetry.scripts]
train = 'simplegep.main:main'

# ****** cifar10 ******
# single train
train_no_dp_cifar10 = 'simplegep.main:run_no_dp_cifar10'
train_dp_sgd_cifar10 = 'simplegep.main:run_dp_sgd_cifar10'
train_gep_cifar10 = 'simplegep.main:run_gep_cifar10'

# single train with GP
train_gp_dp_sgd_cifar10 = 'simplegep.main:run_gp_dp_sgd_cifar10'

# sweep
sweep_no_dp_cifar10 = 'simplegep.main:sweep_no_dp_cifar10'
sweep_dp_sgd_cifar10 = 'simplegep.main:sweep_dp_sgd_cifar10'
sweep_gep_cifar10 = 'simplegep.main:sweep_gep_cifar10'

# ******* putEMG **********
# single train
train_no_dp_putemg = 'simplegep.main:run_no_dp_putemg'
train_dp_sgd_putemg = 'simplegep.main:run_dp_sgd_putemg'


# single train with GP
train_gp_dp_sgd_putemg = 'simplegep.main:run_gp_dp_sgd_putemg'

# sweep
sweep_no_dp_putemg = 'simplegep.main:sweep_no_dp_putemg'
sweep_dp_sgd_putemg = 'simplegep.main:sweep_dp_sgd_putemg'
sweep_gep_putemg = 'simplegep.main:sweep_gep_putemg'

# ****** Toronto UHN Typing Dataset (a.k.a keypressemg)  ******
# single train
train_no_dp_keypressemg = 'simplegep.main:run_no_dp_keypressemg'
train_dp_sgd_keypressemg = 'simplegep.main:run_dp_sgd_keypressemg'

# sweep
sweep_no_dp_keypressemg = 'simplegep.main:sweep_no_dp_keypressemg'
sweep_dp_sgd_keypressemg = 'simplegep.main:sweep_dp_sgd_keypressemg'




[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
